version: '3.9'

services:
  php:
    build: .
    ports:
      - '8080:80'
    healthcheck:
      test: curl --fail http://nginx || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  nginx:
    image: nginx:latest